export const construtorMapping = {
    barChart: 'BarChart',
    boxPlot: 'BoxPlot',
    bubbleChart: 'BubbleChart',
    bubbleOverlay: 'BubbleOverlay',
    cboxMenu: 'CboxMenu',
    compositeChart: 'CompositeChart',
    dataCount: 'DataCount',
    dataGrid: 'DataGrid',
    dataTable: 'DataTable',
    geoChoroplethChart: 'GeoChoroplethChart',
    heatMap: 'HeatMap',
    htmlLegend: 'HtmlLegend',
    legend: 'Legend',
    lineChart: 'LineChart',
    numberDisplay: 'NumberDisplay',
    pieChart: 'PieChart',
    rowChart: 'RowChart',
    scatterPlot: 'ScatterPlot',
    selectMenu: 'SelectMenu',
    seriesChart: 'SeriesChart',
    sunburstChart: 'SunburstChart',
    textFilterWidget: 'TextFilterWidget',
};
